name: Snyk Security

on:
  pull_request:
    branches: [main]
  schedule:
    - cron: '12 8 * * 2'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  snyk:
    permissions:
      actions: read
      contents: read
      statuses: read
      security-events: write
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Snyk CLI
        uses: snyk/actions/setup@9adf32b1121593767fc3c057af55b55db032dc04

      # Run Snyk Code (SAST) analysis and produce SARIF for GitHub Code Scanning.
      - name: Code (SAST) test
        run: snyk code test --sarif > snyk-code.sarif
        continue-on-error: true

      - name: PHP dependency test
        uses: snyk/actions/php@9adf32b1121593767fc3c057af55b55db032dc04 # v1.0.0
        continue-on-error: true

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@99df26d4f13ea111d4ec1a7dddef6063f76b97e9 # v4.37.0
        with:
          sarif_file: snyk-code.sarif